---
format:
  pdf:
    number-depth: 3
  html:
    number-depth: 3
---

# Teknis Penulisan dan Format Skripsi

Setiap institusi memeiliki standard dan format tersendiri dalam penulisan dan pengetikan laporan penelitian. Dalam hal ini, Fakultas Psikologi YARSI juga memiliki panduan teknis yang berlaku secara umum untuk mahasiswa yang mengerjakan Skrpsi. Panduan teknis ini diharapkan dapat mendorong keseragaman luaran skripsi mahasiswa. Mahasiswa dapat mengunduh *template* format skripsi pada tautan [ini](https://drive.google.com/file/d/1Qxn2S_09NiJaV__Aqd3o9aqdDlvM-dWr/view?usp=sharing).

## Panduan Umum Teknis Penulisan Skripsi

### Media dan Layout Skripsi

#### Layout kertas

Naskah proposal skripsi dan skripsi, baik yang dalam bentuk digital maupun cetak, ditulis di kertas ukuran A4 (210 x 297 mm) dengan orientasi *portrait*, kecuali pada bagian-bagian tertentu yang membutuhkan penulisan dengan orientasi *landscape*. Naskah skripsi cetak menggunakan kertas dengan berat 80 gram dan tidak dicetak secara bolak-balik.  Batas tepi (*margins*) pengetikan adalah masing-masing 4 cm untuk tepi atas dan tepi kiri, dan 3 cm untuk tepi kanan dan tepi bawah.

#### Jarak baris

-   Penulisan naskah menggunakan jarak antara dua baris dalam kalimat (spasi) dengan ukuran 1,5 (*1,5 line spacing*). Sementara itu, penggunaan spasi 1 (*single line* *spacing*) hanya dipergunakan untuk:
-   kutipan langsung lebih dari 3 baris atau \> 40 kata;
-   judul tabel dan judul gambar yang memerlukan lebih dari satu baris;
-   keterangan yang menjelaskan : tabel, gambar, dan rumus;
-   penulisan daftar pustaka;
-   penulisan Abstrak dan Abstract;
-   Judul anak sub-bab dan turunannya yang memerlukan lebih dari satu baris

Jarak baris penulisan bagian inti proposal dan skripsi juga perlu memperhatikan hal-hal berikut ini:

-   Jarak antara judul bab (*heading* level 1) dengan teks pertama yang ditulis, atau antara judul bab dan judul anak bab (*heading* level 2) adalah dua spasi
-   Jarak antara judul anak bab dengan baris pertama teks adalah dua spasi
-   Jarak antara baris akhir teks dengan judul anak bab berikutnya adalah dua spasi
-   Jarak antara teks dengan tabel, gambar, grafik, diagram, atau judulnya adalah dua spasi
-   Alinea baru diketik menjorok kedalam lima (5) ketukan dari marjin kiri teks

#### Jenis Huruf

Jenis huruf (*font*) yang digunakan dalam skripsi adalah Times New Romandengan ukuran 12pt, kecuali untuk penulisan judul skripsi di sampul luar dan halaman judul. Jenis dan ukuran *font* yang digunakan pada sampul dan halaman judul akan dibahas di bagian berikutnya.

#### Penggunaan Huruf Cetak Miring (*Italic*)

a.  Penggunaan huruf cetak miring (*italic*) dipakai apabila:
b.  Menggunakan istilah, kata, atau singkatan yang berasal dari kata asing. Contoh: *self efficacy*, *conscientiousness*, dan lain-lain.
c.  Judul dari sebuah buku, publikasi secara periodik, atau dalam bentuk *microfilm*. Contoh: *American Psychologist*
d.  Nama dari spesies dan varitas. Contoh: *Macaca mulatta*
e.  Huruf yang digunakan dalam lambang statistik atau matematika. Contoh: *t-test*; *r* = 0,2; *F*(1,53) = 3,234
f.  Nilai tes atau skala. Contoh: MMPI *scales*
g.  Daftar referensi dari nomer volume jurnal secara periodik. Contoh: *26*, 47-67

### Format Sampul (Cover) Luar

Sampul skripsi dibuat dari kertas buffalo atau yang sejenis dan diperkuat dengan karton dan dilapisi plastik (*hardcover*). Tulisan yang dicetak dalam sampul harus sama dengan tulisan pada halaman judul dengan menggunakan tinta berwarna emas. Sampul skripsi berwarna ungu, disesuaikan dengan lambang Fakultas Psikologi Universitas YARSI. Format penulisan sampul luar sesuai dengan ketentuan berikut:

1.  Judul dan Anak Judul

    a.  Judul skripsi ditulis di baris paling atas, dengan huruf kapital (*uppercase*) dengan menggunakan tipe huruf (*font type*) Times New Roman ukuran 14 pt. Jarak dari tepi atas kertas sekurang-kurangnya 6 cm.
    b.  Judul yang panjang ditulis menjadi dua baris atau lebih, dengan pemotongan judul yang logis, sesuai dengan kaidah Bahasa Indonesia. Jarak antara kedua baris judul diatur agak rapat.
    c.  Sub Judul (jika ada) ditulis dibawah judul, dengan huruf kapital semua, ukuran *font* 13 pt, dengan diberi jarak dari judul sekitar 1,5 cm dari baris judul yang paling bawah.
    d.  Anak judul yang panjang ditulis menjadi dua baris atau lebih, dengan pemotongan judul yang logis, sesuai dengan kaidah Bahasa Indonesia. Jarak antara kedua baris diatur agak rapat.
    e.  Judul maupun anak judul tidak diakhiri dengan tanda titik (.).
    f.  Jarak spasi Judul adalah 1 spasi.

2.  Tulisan SKRIPSI

    a.  Tulisan SKRIPSI ditulis dengan *uppercase*, diletakkan di tengah, dengan jenis dan besar huruf yang sama dengan anak judul.

    b.  Letak tulisan SKRIPSI sekitar 2,5 cm dibawah anak judul. Kalau tidak ada anak judul, letak tulisan SKRIPSI sekitar 5 cm dari baris judul yang paling bawah.

    c.  Di bawah tulisan SKRIPSI, dengan jarak sekitar 1 cm, dicantumkan kalimat seperti berikut:

        ```{=latex}
        \setmainfont{Times New Roman}
        \begin{center} 
        \textbf{SKRIPSI}

        Diajukan untuk menempuh Ujian \\Sarjana Strata 1  pada Fakultas Psikologi
        \end{center} 
        ```

3.  Nama dan NPM Mahasiswa

    a.  Nama mahasiswa ditulis dengan *uppercase*, diletakkan di tengah dengan jenis dan besar huruf yang sama dengan anak judul.

    b.  Letak tulisan nama mahasiswa sekitar 2,5 cm di bawah tulisan Universitas YARSI

    c.  NPM mahasiswa ditulis dengan huruf kapital semua, diletakkan dI tengah di bawah nama mahasiswa, dengan jenis dan besar huruf yang sama dengan anak judul.

    d.  Jarak spasi untuk Nama mahasiswa dan NPM adalah 1 spasi. Contoh:

        ```{=latex}
        \setmainfont{Times New Roman}
        \begin{center} 
        \textbf{ESTI INDRIYANI\\
        NPM 1602008078}
        \end{center} 
        ```

4.  Logo Universitas YARSI

    Logo YARSI bergaris tengah 3,5 cm. Titik tengahnya terletak di tengah-tengah di antara baris NPM mahasiswa dengan baris nama universitas (Universitas YARSI). File gambar Logo YARSI dapat diunduh di [sini](https://drive.google.com/file/d/11trNCsQdbG1ErnliS7XHTR6DsUtex-Xv/view?usp=sharing).

5.  Nama Universitas, Fakultas, Kota, dan Tahun Penyusunan

    a.  Tulisan nama universitas (Universitas YARSI), fakultas, kota, dan tahun penyusunan skripsi ditulis dengan *uppercase*, cetak tebal, dengan jenis dan besar huruf yang sama dengan anak judul, disusun secara berurutan per baris, dengan jarak 1,5 spasi

    b.  Tahun penyusunan skripsi yang ditulis paling bawah, diletakkan sekitar 3,5 cm dari tepi bawah kertas. Contoh:

        ```{=latex}
        \setmainfont{Times New Roman}
        \begin{center} 
        \textbf{FAKULTAS PSIKOLOGI\\
        UNIVERSITAS YARSI\\
        JAKARTA \\
        2024
        }
        \end{center}
        ```

Penempatan tulisan pada sampul luar (yang sama dengan halaman judul), harus memperhatikan keseimbangan jarak margin atas, bawah, kiri, dan kanan. Contoh format *cover* dan halaman judul skripsi dapat dilihat di [Lampiran 6](#_Lampiran_6_Contoh).

## Penulisan Bagian Awal Skripsi:

### Penomoran Halaman

Penomoran halaman pada bagian awal skripsi mengikuti panduan berikut ini:

a.  Penomoran halaman bagian awal skripsi, mulai dari Kata Pengantar sampai dengan halaman Daftar Lampiran, menggunakan angka romawi kecil
b.  Halaman Judul hingga Halaman Pengesahan tidak diberi nomor urut halaman, tetapi diperhitungkan sebagai halaman i hingga halaman iv (nomor halaman tersebut tidak diketik).
c.  Penulisan nomor halaman dimulai dari Halaman Kata Pengantar (halaman v)
d.  Halaman Abstrak sampai dengan halaman Daftar Lampiran diberi nomor dengan angka romawi kecil yang merupakan kelanjutan dari Halaman Judul hingga Halaman Pengesahan
e.  Nomor halaman diletakkan pada bagian bawah persis di tengah-tengah (*center alignment*)

### Penulisan Judul Bagian

1.  Tiap judul *heading* level 1 diketik di halaman baru dengan huruf kapital hanya pada awal kata. Penulisan ditempatkan di tengah (*center alignment*), dicetak tebal (*bold*), dan tidak diberi garis bawah.
2.  Judul *heading* level 1 pada bagian awal skripsi mencakup: 
    -   Lembar Pernyataan
    -   Halaman Persetujuan Pembimbing
    -   Halaman Pengesahan
    -   Halaman Kata Pengantar
    -   Halaman Ucapan Terima Kasih
    -   Halaman Abstrak
    -   Halaman Abstract
    -   Daftar Isi
    -   Daftar Tabel
    -   Dafter Gambar
    -   Daftar Lampiran

### Penulisan Lembar Pernyataan

Judul Lembar Pernyataan ditulis dengan huruf besar (*uppercase*), cetak tebal (*bold*), spasi 1,5, dan terletak di tengah (*center alignment*). Pernyataan orisinalitas diketik dengan jarak dua spasi dari judul Lembar Pernyataan. Pernyataan orisinalitas skripsi dituliskan sebagai berikut:

“Saya menyatakan bahwa skripsi yang saya susun sebagai syarat memperoleh gelar sarjana ini merupakan karya tulis saya sendiri. Adapun bagian-bagian tertentu dalam penlisan skripsi ini saya kutip dari hasil karya orang lain yang telah dituliskan sumbernya secara jelas sesuai dengan norma, kaidah, dan etika penulisan ilmiah. Saya bersedia menerima sanksi yang sesuai dengan peraturan perundangan yang berlaku apabila di kemudian hari ditemukan bukti tindak plagiarisme dalam skripsi ini.”

Kota dan tanggal penandatanganan surat pernyataan diketik berjarak dua spasi di bawah paragraf pernyataan dengan format rata kanan. Setelah itu, penulisan “Yang menyatakan,” ditulis dengan jarak satu spasi di bawah penulisan kota dan tanggal, kemudian diikuti dengan ruang tanda tangan sebesar 3 spasi, lalu penulisan nama lengkap dan NPM mahasiswa. Mahasiswa menandatangani Lembar Pernyataan di atas meterai Rp10.000 pada bagian yang telah disediakan.

### Penulisan Halaman Persetujuan Pembimbing

1.  Judul skripsi diketik dengan jarak 4 cm dari tepi kertas bagian atas. Seluruh kalimat judul diketik dengan huruf kapital, dengan jarak antar baris yang rapat.
2.  Baris sub judul diketik di bawah judul, dengan jarak sekitar 1 cm dari baris terakhir judul. Semua diketik dengan huruf kapital.
3.  Nama mahasiswa diketik di bawah sub judul, dengan jarak sekitar 1 cm dari baris terakhir sub judul. Semua diketik dengan huruf kapital
4.  NPM diketik di bawah nama mahasiswa, dengan jarak satu spasi.
5.  Waktu pemberian persetujuan hanya ditulis bulan dan tahunnya, diketik di belakang kata ‘JAKARTA’.
6.  *Lay out* ‘menyetujui’, ‘Pembimbing Utama’, diatur dengan memperhatikan keseimbangan pada halaman ini. Nama pembimbing berjarak 4 cm dari tepi kertas bagian bawah.

### Penulisan Halaman Pengesahan

Judul Halaman Pengesahan ditulis dengan huruf besar (*uppercase*), cetak tebal (bold), dan terletak di tengah (*center alignment*). Halaman pengesahan diketik dengan jarak dua spasi dari judul Halaman Pengesahan.

Halaman Pengesahan diawali dengan pernyataan “Skripsi ini diajukan oleh”, lalu diikuti dengn identitas penulis yang meliputi: Nama penulis, NPM, Program Studi (Psikologi) dan Judul Skripsi. Pernyataan dan identitas tersebut dituliskan pada baris berbeda, rata kiri dan berjarak satu spasi antarbaris.

Berikan jarak 2 spasi antara identitas penulis dengan pernyataan pengesahan skripsi, yang dituliskan sebagai berikut:

“Telah berhasil dipertahankan di hadapan Dewan Penguji dan diterima sebagai bagian persyaratan yang diperlukan untuk memperoleh gelar Sarjana Psikologi pada Fakultas Psikologi Universitas YARSI, pada tanggal ...... (lengkapi dengan tanggal ujian skripsi Anda).”

Berikan jarak 3 spasi lalu tuliskan “DEWAN PENGUJI” dengan huruf besar (*uppercase*), dan terletak di tengah (*center alignment*). Beri jarak 3 spasi lalu tuliskan daftar nama dewan penguji skripsi dengan mencantumkan nama, ruang untuk membubuhkan tanda tangan dan posisi mereka pada proses persidangan (apakah sebagai ketua atau anggota dewan penguji).

Pada bagian paling bawah halaman pengesahan dilengkapi dengan tanda tangan Dekan sebagai pihak yang mengetahui dan mengesahkan skripsi. Tulisan “Mengetahui,” ditulis dengan jarak dua spasi di bawah penulisan nama dan tandatangan penguji ketiga, kemudian diikuti dengan ruang tanda tangan sebesar 4 spasi, lalu penulisan nama lengkap Dekan. Seluruh dewan penguji dan dekan menandatangani Lembar Pengesahan dan bubuhkan cap fakultas pada tandatangan dekan sebagai bukti keabsahan skripsi.

### Penulisan Halaman Kata Pengantar dan Ucapan Terimakasih

Halaman Kata Pengantar dan Ucapan Terimakasih dituliskan dengan ketentuan berikut:

1.  Jarak spasi dalam pengetikan Kata Pengantar dan Ucapan Terimakasih adalah satu spasi.
2.  Judul ditulis dengan huruf besar (*uppercase*), cetak tebal (*bold*), dan terletak di tengah (*center alignment*). Jarak antara judul dengan teks pertama Kata Pengantar dan Ucapan Terimakasih adalah dua spasi.
3.  Penulisan Kata Pengantar dan Ucapan Terimakasih masing-masing tidak lebih dari satu halaman (maksimal satu halaman).

### Penulisan Halaman Abstrak dan Abstract

Pengetikan halaman Abstrak dan *Abstract* perlu memperhatikan beberapa hal di bawah ini:

1.  Jarak spasi dalam pengetikan abstrak adalah satu spasi
2.  Jarak antara judul Abstrak dan *Abstract* dengan teks pertama abstrak adalah dua spasi
3.  Penulisan abstrak penelitian sedapat mungkin tercakup dalam satu alinea saja, atau setidaknya tidak lebih dari 2 alinea
4.  Jika jumlah abstrak lebih dari satu alinea, jarak antara alinea yang satu dengan alinea yang lain adalah satu spasi

### Penulisan Daftar Isi, Daftar Tabel, Daftar Gambar, dan Daftar Lampiran

Pengetikan halaman Daftar Isi, Daftar Tabel, Daftar Gambar dan Daftar Lampiran dituliskan dengan ketentuan berikut:

1.  Jarak spasi dalam pengetikan isi dari masing-masing daftar adalah satu spasi.
2.  Jarak antara judul dan isi dari masing-masing daftar isi, tabel, gambar dan lampiran adalah dua spasi.

Format dan contoh penulisan bagian awal skripsi dapat dilihat pada [Lampiran 7](#_Lampiran_7_Contoh).

## Penulisan Bagian Inti Skripsi

### Penomoran Bab

Penomoran Bab dalam bagian inti skripsi ditulis menggunakan angka Arab diikiuti dengan tanda titik (.). Judul Bab (*heading* level 1) ditulis menyambung dengan nomor Bab dengan huruf kapital dan diletakkan di bagian tengah-atas halaman, dengan jenis huruf tebal (*bold*). Sub Bab (*heading* level 2) diberi nomor dengan menggunakan angka Arab, diikuti dengan tanda titik, terletak di kiri halaman, dengan jenis huruf tebal. Judul sub Bab (*heading* level 2) ditulis dengan menggunakan kapitalis huruf awal kata.

Penomoran Anak Sub Bab dengan menggunakan angka Arab, diikuti dengan tanda titik dan diletakkan di rata kiri dari halaman. Judul Anak Sub Bab (*heading* level 3) ditulis dengan menggunakan kapitalisasi huruf awal dengan jenis huruf tebal. Penomoran Anak-Anak Sub Bab dengan menggunakan huruf kecil, diikuti dengan tanda titik. Judul Anak-Anak Sub Bab (*heading* level 4) ditulis dengan kapitalis huruf awal kata, dan menggunakan indensi tunggal. Jenis huruf yang digunakan regular. Penulisan *heading* 5 dan seterusnya tidak mengunakan menggunakan format penomoran, judul bab ditulis rata kiri dan cetak miring (*italic*) diakhiri dengan titik.

Penulisan setiap judul bab dan anak bab menggunakan menu *heading styles* pada micosoft word dengan mengikuti ketentuan *heading* dan *subheading* *level* menurut Format APA. Terdapat lima *level heading* (sub bab) menurut APA: Level 1 (Bab utama), Level 2 (anak bab), Level 3 (anak bab dari level 2) dan seterusnya hinggal Level 5. Penggunaan heading level pada tulisan bergantung pada kompleksitas tulisan. Untuk memahami lebih lanjut mengenai format tiap level menurut Format APA dan contohnya, lihat @tbl-headinglevel.

### Penomoran Halaman

Pemberian nomor pada bagian inti skripsi ditetapkan sebagai berikut:

a.  Penomoran bagian inti skripsi, mulai dari Bab 1 Pendahuluan sampai dengan Bab 6 Kesimpulan dan Saran, menggunakan angka Arab.
b.  Pada tiap halaman yang memiliki judul bab, mulai dari Bab 1 Pendahuluan hingga Bab 6 Kesimpulan dan Saran, nomor halaman diletakkan pada bagian bawah (*footer*) persis di tengah, berjarak tiga spasi dari marjin bawah (baris akhir teks pada halaman itu)
c.  Nomor halaman selain yang dijelaskan pada poin b di atas diletakkan pada bagian atas sebelah kanan, berjarak tiga spasi dari margin atas (baris pertama teks pada halaman itu) dan angka terakhir nomor halaman itu lurus dengan *margin* kanan.

::: {#tbl-headinglevel tbl-colwidths="[15,85]"}
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Level    | Format                                                                                                                                        |
+:========:+:==============================================================================================================================================+
| **1**    | **Ditulis di Tengah, Tebal, *Title Case***                                                                                                    |
|          |                                                                                                                                               |
|          | Teks dimulai sebagai paragraf baru.                                                                                                           |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| **2**    | **Rata Kiri, Tebal, *Title Case***                                                                                                            |
|          |                                                                                                                                               |
|          | Teks dimulai sebagai paragraf baru.                                                                                                           |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| **3**    | ***Rata Kiri, Tebal, Miring, Title Case***                                                                                                    |
|          |                                                                                                                                               |
|          | Teks dimulai sebagai paragraf baru.                                                                                                           |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| **4**    | **Berinden, Tebal, *Title Case*, Diakhiri dengan Titik.** Teks dimulai pada baris yang sama dan berlanjut sebagai paragraf biasa.             |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| **5**    | ***Berinden, Tebal, Miring, Title Case*****, Diakhiri dengan Titik.** Teks dimulai pada baris yang sama dan berlanjut sebagai paragraf biasa. |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------+

: Format dan Contoh Penulisan Heading Level Format APA
:::

### Penulisan Judul Bab

1.  Tiap judul *heading* level 1 diketik di halaman baru dengan huruf kapital hanya pada awal kata. Penulisan ditempatkan di tengah (*center alignment*), dicetak tebal (*bold*), dan tidak diberi garis bawah.
2.  Judul *heading* level 1 pada bagian inti skripsi mencakup:
    -   Bab 1 Pendahuluan
    -   Bab 2 Tinjauan Literatur
    -   Bab 3 Metode Penelitian
    -   Bab 4 Hasil dan Pembahasan
    -   Bab 5 Hasil Penelitian Menurut Tinjauan Islam
    -   Bab 6 Kesimpulan dan Saran
    -   Daftar Pustaka
    -   Lampiran

### Penulisan Kutipan

#### Jenis kutipan

Sertakan kutipan dalam teks ketika Anda merujuk, meringkas, memparafrase, atau mengutip dari sumber lain. Untuk setiap kutipan dalam teks di makalah Anda, harus ada entri yang sesuai dalam Daftar Pustaka. Format penulisan kutipan dalam teks memiliki dua jenis:

1.  Dalam tanda kurung: nama penulis dan tanggal penerbitan (atau informasi yang setara) muncul dalam tanda kurung.

    Misalnya: Pemberitaan yang tidak berimbang dapat mendistorsi persepsi masyarakat terhadap konsensus para ahli mengenai suatu isu (Burnside, 2016).

2.  Narasi: nama penulis muncul dalam teks berjalan dan tahun publikasi muncul dalam tanda kurung tepat setelah nama penulis.

    Misalnya: ”Burnside (2016) mencatat bahaya liputan berita yang tidak seimbang.”

#### Penulisan kutipan dengan sumber yang tidak lengkap

Kadang penulis menemukan informasi penting untuk dikutip dari sumber tulisan lain, tetapi informasi mengenai sumber kutipan tersebut tidak dapat diketahui secara menyeluruh. Dalam situasi tersebut, penulis tetap wajib menuliskan kutipan yang sesuai dengan kaidah.

#### Penulisan kutipan dari sumber jamak

Apabila kutipan merupakan gagasan dari beberapa publikasi, cantumkan nama akhir dan tahun publikasi semua sumber, dengan menggunakan tanda baca titik koma (;) sebagai pemisah di akhir kutipan, dan diurutkan berdasarkan alfabet nama akhir pengarang.

#### Penulisan kutipan jamak dengan kesamaan nama dan tahun

Ketika penulis mengutip gagasan dari beberapa publikasi, seringkali ditemui gagasan yang serupa yang bersumber dari beberapa artikel yang berbeda dengan penulis yang sama, tahun publikasi yang sama, dan sebagainya. Hal ini dapat menimbulkan kebingungan dan ketidakjelasan dalam pengutipan.

Tata cara dan contoh penulisan dapat dilihat pada @tbl-kutipanteks.

::: {#tbl-kutipanteks}
+-----------------------------------+-------------------------------------------+---------------------------------------+
| Jenis Penulis                     | Kutipan Dalam Kurung                      | Kutipan Naratif                       |
+:==================================+:==========================================+:======================================+
| Satu penulis                      | (Case, 2011)                              | Case (2011)                           |
+-----------------------------------+-------------------------------------------+---------------------------------------+
| Dua penulis                       | (Case & Daristotle, 2011)                 | Case dan Daristotle (2011)            |
+-----------------------------------+-------------------------------------------+---------------------------------------+
| Tiga atau lebih penulis           | (Case dkk., 2011)                         | Case dkk. (2011)                      |
+-----------------------------------+-------------------------------------------+---------------------------------------+
| Penulis kelompok dengan singkatan |                                           |                                       |
+-----------------------------------+-------------------------------------------+---------------------------------------+
| Kutipan pertama                   | (World Health Organization \[WHO\], 2020) | World Health Organization (WHO, 2020) |
+-----------------------------------+-------------------------------------------+---------------------------------------+
| Kutipan selanjutnya               | (WHO, 2020)                               | WHO (2020)                            |
+-----------------------------------+-------------------------------------------+---------------------------------------+
| Penulis kelompok tanpa singkatan  | (Yale University, 2020)                   | Yale University (2020)                |
+-----------------------------------+-------------------------------------------+---------------------------------------+

Contoh Penulisan Kutipan dalam Teks
:::

#### Penulisan kutipan dari sumber sekunder

Saat mengutip sumber sekunder, sebutkan sumber primernya dan tuliskan ”dalam” sumber sekunder yang Anda gunakan. Jika tahun penerbitan sumber utama diketahui, cantumkan juga sumber tersebut dalam kutipan teks (misalnya, ”Rabbitt (1982, dalam Lyon dkk., 2014)”). Jika tahun sumber utama tidak diketahui, hilangkan sumber tersebut dari kutipan dalam teks (misalnya, ”buku harian Allport (dalam Nicholson, 2003)”).

#### Penulisan kutipan dari sumber komunikasi pribadi

Apabila kutipan diambil dari komunikasi pribadi dengan sumber informasi (mis., wawancara pribadi, percakapan telepon, email, surat, dsb.), cantumkan nama inisial dan nama akhir sumber, diikuti dengan keterangan tanggal komunikasi dilakukan. Kutipan yang diambil dari komunikasi personal tidak dicantumkan dalam Daftar Pustaka.

#### Penulisan kutipan langsung

Jika kutipan merupakan kutipan langsung merupakan kalimat pendek (kurang dari 40 kata), tambahkan tanda kutip diawal dan akhir teks yang dikutip. Jika kutipan langsung merupakan kalimat panjang (lebih dari 40 kata) ataupun paragraf yang terdiri dari sejumlah kalimat, tempatkanlah kutipan ini terpisah dari teks, berjarak satu spasi, rata kiri, dan masuk 5 ketukan dari *margin* kiri, tanpa mengubah jenis maupun ukuran tulisan. Untuk kedua jenis kutipan langsung, tambahkan detail halaman sumber kutipan yang diuliskan setelah tahun terbit dan koma.

#### Penulisan kutipan bersumber dari media massa

Kutipan yang diambil dari artikel koran, majalah, ataupun halaman web pada umumnya mengikuti format standar yang berlaku, yaitu dengan mencantumkan nama akhir penulis dan tahun publikasinya. Untuk artikel yang nama penulisnya tidak tertera, cantumkan judul artikel di dalam tanda kutip dan tahun penerbitannya (khusus untuk artikel koran, cantumkan juga nomor halaman). Jika kutipan diambil dari halaman web, URL dicantumkan di daftar pustaka, bukan di badan tulisan.

Rangkuman tata cara format dan penulisan kutipan dapat dilihat di @tbl-rangkuman.

### Penggunaan Tabel dan Gambar/Grafik

Terkadang, peneliti butuh menampilkan data dan informasi yang cukup kompleks ketika menguraikan temuan penelitiannya. Dalam kasus seperti ini, tabel dan gambar/grafik dapat membantu penyederhanaan tampilan data, sehingga peneliti cukup berfokus untuk menguraikan hal-hal penting dari data ketika mendeskripsikan data dalam tulisan. Tabel dan gambar juga berfungsi mempermudah pembaca untuk memahami informasi yang perlu ditampilkan secara lebih ringkas dan terorganisasi. Selain itu, gambar atau grafik juga perlu ditampilkan untuk memaparkan instrumen-instrumen penelitian tertentu yang lebih dapat dengan mudah dipahami melalui penjelasan secara visual daripada verbal.

Pada intinya, tabel dan gambar dalam skripsi digunakan hanya sebagai alat bantu bagi peneliti untuk menampilkan informasi yang kompleks atau banyak. Peneliti tidak perlu menggunakan tabel apabila informasi yang ingin ditampilkan hanya sedikit dan sederhana (misalnya, data hasil analisis korelasi antara dua variabel, hasil analisis reliabilitas alat ukur). Penggunaan tabel dalam kasus demikian hanya akan menimbulkan pengulangan atau redundansi dari apa yang telah dijelaskan dalam uraian tertulis, yang pada akhirnya dapat mengurangi keringkasan naskah.

Tabel dan gambar harus ditampilkan pada posisi yang berdekatan dengan tempat pembahasannya dalam teks utama. Tabel dan gambar harus diberi nomor dan dikutip dalam teks secara berurutan dengan menggunakan angka Arab (yaitu Tabel 1, Tabel 2; Gambar 1, Gambar 2, dst.). Panduan format penulisan dan tampilan tabel dan gambar dapat dilihat pada [Lampiran 8](#_Lampiran_8_Format).

::: {#tbl-rangkuman}
+--------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Situasi                                                                                                            | Format penulisan kutipan                                                                                                                                                                                                                                                                              | Contoh pengutipan                                                                                                                                                                                                                                                                                     |
+:===================================================================================================================+:======================================================================================================================================================================================================================================================================================================+:======================================================================================================================================================================================================================================================================================================+
| Sumber informasi tidak lengkap                                                                                     |                                                                                                                                                                                                                                                                                                       |                                                                                                                                                                                                                                                                                                       |
+--------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Tidak ada nama penulis                                                                                             | Gunakan judul tulisan                                                                                                                                                                                                                                                                                 | (Kepemimpinan Transformasional di Kalangan Generasi Z, 2020)                                                                                                                                                                                                                                          |
+--------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Tidak ada tanggal publikasi                                                                                        | Tulis “n.d.” untuk menandakan ”*no date*” atau tidak ada tanggal                                                                                                                                                                                                                                      | (Harris, n.d.)                                                                                                                                                                                                                                                                                        |
+--------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Tidak ada nomor halaman                                                                                            | Tidak perlu cantumkan halaman, atau gunakan alternatif petunjuk lokasi lainnya (seperti: bab, paragraf, nomor slide, nomor tabel, petunjuk waktu pada video, dsb.)                                                                                                                                    | (Harris, 2020, 14:32) atau (Harris, 2020)                                                                                                                                                                                                                                                             |
+--------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Sumber informasi jamak                                                                                             | Cantumkan nama akhir dan tahun publikasi semua sumber, dengan menggunakan tanda baca titik koma (;)                                                                                                                                                                                                   | (Eysenck, 1967; McCrae, 2000; Smith, 2015, 2017)                                                                                                                                                                                                                                                      |
+--------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Sumber jamak dengan kesamaan nama dan tahun                                                                        |                                                                                                                                                                                                                                                                                                       |                                                                                                                                                                                                                                                                                                       |
+--------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Beberapa tulisan yang dipublikasikan oleh penulis sama di tahun yang sama.                                         | Tambahkan huruf kecil setelah tahun                                                                                                                                                                                                                                                                   | (Cooper, 2020a)                                                                                                                                                                                                                                                                                       |
|                                                                                                                    |                                                                                                                                                                                                                                                                                                       |                                                                                                                                                                                                                                                                                                       |
|                                                                                                                    |                                                                                                                                                                                                                                                                                                       | (Cooper, 2020b)                                                                                                                                                                                                                                                                                       |
+--------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Penulis berbeda dengan nama belakang sama                                                                          | Tambahkan singkatan nama depan                                                                                                                                                                                                                                                                        | (H. Taylor, 2019)                                                                                                                                                                                                                                                                                     |
|                                                                                                                    |                                                                                                                                                                                                                                                                                                       |                                                                                                                                                                                                                                                                                                       |
|                                                                                                                    |                                                                                                                                                                                                                                                                                                       | (B. J. Taylor, 2019)                                                                                                                                                                                                                                                                                  |
+--------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Beberapa tulisan yang dibuat oleh lebih dari 3 penulis, penulis pertama sama dan diterbitkan pada tahun yang sama. | Tuliskan nama penulis kedua, ketiga, keempat, dst (sebanyak mungkin) hingga terlihat perbedaan antara tulisan yang dikutip.                                                                                                                                                                           | (Hu, Creed, dkk., 2015)                                                                                                                                                                                                                                                                               |
|                                                                                                                    |                                                                                                                                                                                                                                                                                                       |                                                                                                                                                                                                                                                                                                       |
|                                                                                                                    |                                                                                                                                                                                                                                                                                                       | (Hu, Hood, dkk., 2015)                                                                                                                                                                                                                                                                                |
+--------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Sumber sekunder                                                                                                    | Sebutkan sumber primernya dan tuliskan ”dalam”                                                                                                                                                                                                                                                        | Rabbitt (1982, dalam Lyon dkk., 2014)                                                                                                                                                                                                                                                                 |
|                                                                                                                    |                                                                                                                                                                                                                                                                                                       |                                                                                                                                                                                                                                                                                                       |
|                                                                                                                    |                                                                                                                                                                                                                                                                                                       | Allport (dalam Nicholson, 2003)                                                                                                                                                                                                                                                                       |
+--------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Sumber komunikasi pribadi                                                                                          | Cantumkan nama inisial dan nama akhir sumber, diikuti dengan keterangan tanggal komunikasi dilakukan                                                                                                                                                                                                  | S. W. Sarwono (komunikasi personal, 15 Juni 2010)                                                                                                                                                                                                                                                     |
|                                                                                                                    |                                                                                                                                                                                                                                                                                                       |                                                                                                                                                                                                                                                                                                       |
|                                                                                                                    |                                                                                                                                                                                                                                                                                                       | (S. W. Sarwono, komunikasi personal, 15 Juni 2010)                                                                                                                                                                                                                                                    |
+--------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Kutipan langsung                                                                                                   | tambahkan tanda kutip diawal dan akhir teks yang dikutip. Jika kutipan langsung merupakan kalimat panjang (lebih dari 40 kata) ataupun paragraf yang terdiri dari sejumlah kalimat, tempatkanlah kutipan ini terpisah dari teks, berjarak satu spasi, rata kiri, dan masuk 5 ketukan dari margin kiri | Berry, dkk. (2002, hal. 3) mendefinisikan psikologi lintas budaya sebagai:                                                                                                                                                                                                                            |
|                                                                                                                    |                                                                                                                                                                                                                                                                                                       |                                                                                                                                                                                                                                                                                                       |
|                                                                                                                    |                                                                                                                                                                                                                                                                                                       | “…*study of similarities and differences in individual individual psychological functioning in various cultural and ethnocultural groups; of the relationships between psychological variables and socio-cultural, ecological, and biological variables; and of ongoing changes in these variables*.” |
+--------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Sumber media massa                                                                                                 | Mencantumkan nama akhir penulis dan tahun publikasinya                                                                                                                                                                                                                                                | (“Penanganan Ledakan Lamban”, 2010, hal. 1)                                                                                                                                                                                                                                                           |
|                                                                                                                    |                                                                                                                                                                                                                                                                                                       |                                                                                                                                                                                                                                                                                                       |
|                                                                                                                    |                                                                                                                                                                                                                                                                                                       | (“Melacak ‘Babi’ Dalam Vaksin”, 2010)                                                                                                                                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Rangkuman Format Penulisan Kutipan
:::

## Penulisan Bagian Akhir Skripsi

### Penomoran Halaman

a.  Pemberian nomor pada bagian akhir skripsi dilakukan sebagai berikut:
b.  Penomoran bagian akhir skripsi, mulai dari Daftar Pustaka sampai dengan Riwatat Hidup (jika ada) menggunakan angka arab.

Nomor halaman diletakkan pada bagian atas sebelah kanan berjarak tiga spasi dari margin atas (baris pertama teks pada halaman itu) dan angka terakhir nomor halaman itu lurus dengan marjin kanan.

### Penulisan Judul Bagian

1.  Tiap judul *heading* level 1 diketik di halaman baru dengan huruf kapital hanya pada awal kata. Penulisan ditempatkan di tengah (*center alignment*), dicetak tebal **(*bold*)**, dan tidak diberi garis bawah.
2.  Judul *heading* level 1 pada bagian inti skripsi mencakup:
    -   Daftar Pustaka
    -   Lampiran

### Penulisan Daftar Pustaka

Terdapat berbagai cara penulisan Daftar Pustaka. Setiap kelompok ilmu masing-masing memiliki cara penulisan daftar pustaka masing-masing. Dalam hal ini, Fakultas Psikologi YARSI mangacu pada sistem publikasi karya ilmiah Format APA.

Daftar Pustaka dituliskan berurutan berdasarkan urutan huruf depan nama belakang pengarang. Terdapat beberapa bagian penting yang perlu diperhatikan mengenai penyusunan Daftar Pustaka, yaitu mencakup pengarang, tahun publikasi, judul publikasi, informasi publikasi (untuk buku), nomor volume dan isu (untuk artikel yang diterbitkan secara periodikal), pernyataan pengaksesan (untuk informasi yang diambil dari internet), serta alamat *Uniform Resource Locators* (URL, untuk sumber informasi yang diambil dari di internet) atau *Digital Object Identifiers* (DOI, untuk dokumen digital yang memiliki DOI).

Terdapat empat elemen utama dalam penulisan referensi, yaitu pengarang, tahun publikasi, judul publikasi, dan sumber publikasi. Berikut ini penjelasan lebih lanjut mengenai keempat elemen tersebut:

1.  Pengarang

    -   Pengarang adalah individu yang bertanggung jawab dalam menuliskan atau membuat karya yang dipublikasikan.
    -   Pengarang bisa berupa individu, beberapa orang penulis, sebuah organisasi (seperti: perusahaan, instansi pemerintah, kelompok riset, dsb).
    -   Pengarang juga bisa *content creator* dalam bentuk publikasi digital (audio atau audio visual), sutradara sebuah film, dsb.
    -   Gunakan satu spasi di antara inisial nama

    Sejumlah format penulisan pengarang dapat dilihat pada @tbl-formatnamadafpus.

::: {#tbl-formatnamadafpus}
+-------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Pengarang                                                                           | Format                                                                                                        | Contoh                                                                                                                                                                                                                                                          |
+:====================================================================================+:==============================================================================================================+:================================================================================================================================================================================================================================================================+
| Pengarang tunggal                                                                   | Nama pengarang ditulis dengan nama akhir di awal, diikuti inisial nama depan                                  | Wright, C. E.                                                                                                                                                                                                                                                   |
+-------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Pengarang jamak                                                                     | Penulisan antar nama dipisahkan dengan tanda koma (,).  Gunakan *ampersand* (&) di antara dua                 | Prieto, L. R., Siegel, Z. D., & Kaiser, D. J.                                                                                                                                                                                                                   |
+-------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Pengarang \> 20                                                                     | Tuliskan nama depan hingga penulis ke-19 dan diikuti dengan tiga titik (...), lalu nama penulis terakhir.     | Pegion, K., Kirtman, B. P., Becker, E., Collins, D., LaJoie, E., Burgman, R., Bell, R., DelSole, R., Min, D., Zhu, Y., Li, W., Sinsky, E., Guan, H., Gottschalck, J., Metzger, E. J., Barton, N. P., Achuthavarier, D., Marshak, J., Koster, R., . . .  Kim, H. |
+-------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Pengarang adalah organisasi atau instansi                                           | Tuliskan nama lengkap (jangan gunakan singkatan)                                                              | World Health Organization                                                                                                                                                                                                                                       |
+-------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Referensi dari media sosial                                                         | Jika tidak diketahui nama asli dari pengarang, dapat dicantumkan hanya username dengan mengikutkan simbol \@. | \@pewdiepie (tidak diketahui nama asli)                                                                                                                                                                                                                         |
+-------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                     | Jika diketahui nama asli pengarang, dituliskan keduanya (nama asli dan *username*)                            | Trump, D. J. \[\@RealDonadTrump\]                                                                                                                                                                                                                               |
+-------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Tidak ada nama pengarang dalam rujukan                                              | Gunakan ”Anonim”                                                                                              | Anonim                                                                                                                                                                                                                                                          |
+-------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Pengarang dengan nama belakang yang menggunakan karakter atau cara penulisan khusus | Tuliskan namanya secara apa adanya, seperti yang tertulis di naskah yang dijadikan referensi                  | Gómez‐Robledoa, L., & Hernández‐Andrésa, J.                                                                                                                                                                                                                     |
|                                                                                     |                                                                                                               |                                                                                                                                                                                                                                                                 |
|                                                                                     |                                                                                                               | van der Waal, P. N.                                                                                                                                                                                                                                             |
+-------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Format Penulisan Pengarang
:::

2.  Tahun publikasi

    -   Tahun publikasi ditulis di dalam tanda kurung ”()” setelah nama pengarang dan diakhiri dengan tanda titik.

    -   Umumnya hanya dituliskan tahun publikasi, kecuali untuk sumber referensi yang dipublikasikan secara berkala (contoh: koran, blog, video YouTube) atau kegiatan yang dilakukan pada tanggal tertentu (seperti: konferensi, pidato), maka gunakan penanggalan lengkap, yang mencakup tanggal, bulan, dan tahun.

    -   Tanggal pengutipan (*retrieval date*) hanya dituliskan jika sumber informasi yang dikutip cenderung berubah dari waktu ke waktu. Contohnya, informasi yang dikutip dari kamus online, profile media sosial, data statistik, dsb. Tanggal pengutipan tidak perlu dicantumkan jika Anda mengutip dari koran/majalan online. Tanggal pengutipan dituliskan setelah judul, sebelum URL. Tuliskan keterangan ”Dikutip pada” diikuti dengan bulan, tanggal dan tahun.

    Ketentuan umum dalam penulisan tahun publikasi lebih lanjut dapat dilihat pada @tbl-formattahundafpus.

    ::: {#tbl-formattahundafpus}
    +-----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
    | Rujukan                                                   | Format                                                                                                                              | Contoh                                                                                                                             |
    +:==========================================================+:====================================================================================================================================+:===================================================================================================================================+
    | Buku                                                      | Tuliskan tahun *copyright* (dapat dilihat di halaman identitas buku)                                                                | \(2022\)                                                                                                                           |
    +-----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
    | Artikel jurnal ilmiah                                     | Tuliskan tahun volume jurnal tersebut diterbitkan                                                                                   | \(2018\)                                                                                                                           |
    +-----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
    | Artikel daring (koran, majalan, blog)                     | Gunakan tanggal pembaharuan terakhir (*last updated*) dari tulisan yang dikutip (jika dicantumkan)                                  | (2023, 8 September)                                                                                                                |
    +-----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
    | Artikel majalah cetak                                     | Gunakan bulan terbitan majalah                                                                                                      | (2017, Mei)                                                                                                                        |
    +-----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
    | Artikel jurnal ilmiah yang masih dalam proses penerbitan  | Tuliskan (*in press*)                                                                                                               | (*in press*)                                                                                                                       |
    +-----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
    | Artikel daring yang cenderung berubah dari waktu ke waktu | Tuliskan tanggal pengutipan setelah judul, sebelum URL. Tuliskan keterangan ”Dikutip pada” diikuti dengan bulan, tanggal dan tahun. | Worldometer. (n.d.). World population clock. Dikutip pada 20 Oktober, 2020, dari <https://www.worldometers.info/world-population/> |
    +-----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+

    : Ketentuan Penulisan Tahun Publikasi
    :::

3.  Judul publikasi

    -   Merupakan “nama” dari publikasi yang dikutip. Jenis judul publikasi dibagi ke dalam dua kategori besar, yaitu:
    -   Judul karya yang berdiri sendiri, seperti buku, disertasi, film, media sosial, dan artikel daring.
    -   Judul karya yang merupakan bagian dari karya yang lebih besar, seperti artikel jurnal, artikel prosiding, bab pada buku yang disunting, dan episode *podcast*.

    Ringkasan cara penulisan komponen judul publikasi berdasarkan kategori publikasi dapat dilihat pada @tbl-formatjuduldafpus.

    ::: {#tbl-formatjuduldafpus}
    +-----------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------+
    | Jenis Rujukan                                             | Format                                                                                                                    | Contoh                                        |
    +:==========================================================+:==========================================================================================================================+:==============================================+
    | Publikasi yang berdiri sendiri                            | Cetak miring (*italic*) untuk judul, ditulis dengan kapital di awal kalimat (*sentence case*)                             | *Statistical methods for psychology*          |
    +-----------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------+
    | Publikasi yang merupakan bagian dari sekumpulan seri buku | Penulisan teks biasa, ditulis dengan kapital di awal kalimat                                                              | The evolving European model of sports finance |
    +-----------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------+
    | Buku yang memiliki informasi edisi dan volume             | Informasi edisi dan volume ditulis di dalam kurung setelah penulisan judul publikasi, dicetak dengan penulisan teks biasa | *Psikologi Sosial* (Ed. 3)                    |
    |                                                           |                                                                                                                           |                                               |
    |                                                           |                                                                                                                           | *Handbook of social psychology* (Vol. 2)      |
    +-----------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------+

    : Cara Penulisan Komponen Judul Publikasi pada Daftar Pustaka
    :::

4.  Sumber publikasi

    Sumber publikasi merupakan informasi terkait sumber/tempat sebuah karya dipublikasikan. Sama seperti judul, sumber publikasi juga dibagi ke dalam dua kategori, yaitu karya yang berdiri sendiri dan karya yang merupakan bagian dari karya lain yang lebih besar. Contoh penulisan sumber publikasi dapat dilihat pada Tabel 7.

    ::: {#tbl-formatsumberdafpus}
    +-------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | Jenis Rujukan                                   | Format                                                                                                                                                                                                               | Contoh                                                                                                                                                                         |
    +:================================================+:=====================================================================================================================================================================================================================+:===============================================================================================================================================================================+
    | Artikel jurnal                                  | Tuliskan judul, volume, dan isu jurnal, serta nomor halaman artikel dan alamat DOI atau URL. Judul dan volume jurnal ditulis cetak dicetak miring (*italic*), lainnya dicetak biasa. Nomor isu ditulis dalam kurung. | *Criminal justice and behavior, 45*(4), 503-518. https://doi.org/10.1177/0093854817743538                                                                                      |
    +-------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | Buku                                            | Tuliskan nama penerbit dan DOI atau URL (jika ada)                                                                                                                                                                   | Routledge. https://doi.org/10.4324/9781032637242                                                                                                                               |
    +-------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | Bab buku (*book chapter*) dan artikel prosiding | Tuliskan informasi mengenai buku utuhnya (termasuk nama editor, judul buku, edisi/volume buku, nomor halaman, dan penerbit) dan DOI atau URL                                                                         | Dalam S. Koch, F. M. Gloth & R. Nay (Editor), *Medication management in older adults* (hal. 29-42). Springer. https://doi.org/10.1007/978-1-60327-457-9_3                      |
    |                                                 |                                                                                                                                                                                                                      |                                                                                                                                                                                |
    |                                                 |                                                                                                                                                                                                                      | Dalam R. Dienstbier (Editor), *Nebraska Symposium on Motivation: Vol. 49. Cross-cultural differences in perspectives on the self* (pp. 129-174). University of Nebraska Press. |
    +-------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | Halaman web                                     | Tuliskan nama dan URL *website*                                                                                                                                                                                      | BBC. http://www.bbc.com/travel/story/20190929-a-60000-year-old-cure-for-depression                                                                                             |
    +-------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    :::

Untuk memahami lebih lanjut bagaimana penulisan daftar pustaka dengan sumber rujukan yang cukup umum digunakan, Anda dapat mempelajarinya melalui laman [*Common Reference Examples Guide*](https://apastyle.apa.org/instructional-aids/reference-examples.pdf). Selain itu, Anda juga dapat mempelajari “anatomi” daftar pustaka yang bersumber pada artikel jurnal, buku, dan bab buku yang disunting pada laman [ini](https://apastyle.apa.org/instructional-aids/reference-guide.pdf).
