project:
  type: book
  output-dir: docs
  
book: 
  title: "Buku Panduan Penulisan dan Penyusunan Skripsi"
  subtitle: "Edisi ke-4"
  edition: 4
  reader-mode: true
  chapters: 
    - index.qmd
    - 1_pengenalan.qmd
    - 2_kurikulum.qmd
    - 3_topik.qmd
    - 4_strukturproposal.qmd
    - 5_strukturskripsi.qmd
    - 6_teknis.qmd
    - references.qmd
  author:
    - "Sunu Bagaskara"
    - "Sari Zakiah Akmal"
  language: id
  sidebar: 
    style: docked
    search: true
    collapse-level: 0
  cover-image: Cover 2.png
  favicon: Cover 2.png
lang: id
bibliography: references.bib
bibliographystyle: apa

format:
  html:
    theme:
      light: journal
      dark: journal
    css: styles.css
    toc: true
    toc-depth: 3
    number-depth: 2
    breadcrumb: true
    title-block-banner: true
  pdf:
    documentclass: scrbook
    toc: true
    toc-depth: 2
    number-depth: 2
    geometry: "paperwidth=8.27in, paperheight=11.69in, top=0.8in, bottom=1in, left=1in, right=1in"
    pdf-engine: lualatex
    toc-title: "Daftar Isi"
    include-in-header: header.tex        # matikan \maketitle + paket
    #include-before-body: frontmatter.tex # cover + title + verso
    keep-tex: true
    #classoption:
     # - open=any             # cegah sisipan halaman kosong "openright"
    #  - titlepage=false      # judul bab & isi di halaman yang sama
    linkcolor: blue
    urlcolor: blue
    citecolor: blue
    
csl: apa7id.csl