project:
  type: book
  output-dir: docs
  
book: 
  chapters: 
    - index.qmd
    - 1_pengenalan.qmd
    - 2_kurikulum.qmd
    - 3_topik.qmd
    - 4_strukturproposal.qmd
    
lang: id
bibliography: references.bib
bibliographystyle: apa

format:
  html:
    theme: default
    css: styles.css
    toc: false
  pdf:
    documentclass: scrbook
    geometry: "paperwidth=8.27in, paperheight=11.69in, top=0.8in, bottom=1in, left=1in, right=1in"
    pdf-engine: lualatex
    toc-title: "Daftar Isi"
    include-in-header: header.tex        # matikan \maketitle + paket
    #include-before-body: frontmatter.tex # cover + title + verso
    keep-tex: true
    #classoption:
     # - open=any             # cegah sisipan halaman kosong "openright"
    #  - titlepage=false      # judul bab & isi di halaman yang sama