project:
  type: book
  output-dir: docs
  
book: 
  chapters: 
    - index.qmd
    - pengenalan.qmd
    
lang: id
bibliography: references.bib
bibliographystyle: apa

format:
  html:
    theme: default
    css: styles.css
    toc: false
  pdf:
    documentclass: scrreprt
    geometry: margin=1in
    pdf-engine: xelatex
    toc-title: "Daftar Isi"
    include-in-header: header.tex        # matikan \maketitle + paket
    include-before-body: frontmatter.tex # cover + title + verso
    keep-tex: true