# Pendahuluan {.unnumbered}

Dalam perjalanan akademis, penulisan skripsi merupakan salah satu fase krusial yang harus dilalui oleh setiap mahasiswa di perguruan tinggi. Skripsi tidak hanya berfungsi sebagai salah satu syarat untuk mencapai gelar akademik, tetapi juga sebagai bukti kemampuan mahasiswa dalam melakukan penelitian yang sistematis dan mendalam terhadap suatu masalah. Melalui skripsi, mahasiswa ditantang untuk menerapkan pengetahuan yang telah mereka peroleh selama perkuliahan, sekaligus mengembangkan kemampuan analisis, kritis, dan ilmiah mereka.

Tujuan dari buku ini adalah untuk memberikan panduan praktis dan teknis dalam menulis skripsi. Buku ini dirancang untuk membantu mahasiswa dalam merencanakan, melakukan dan menyajikan hasil penelitian mereka dalam bentuk skripsi yang sistematis dan logis. Melalui panduan ini, mahasiswa diharapkan dapat memahami langkah-langkah penulisan skripsi, mulai dari pemilihan topik yang relevan, penyusunan proposal penelitian, pengumpulan dan analisis data, hingga penyajian hasil penelitian dan kesimpulan.

Penggunaan buku ini disarankan untuk dijadikan sebagai acuan atau pedoman selama proses penulisan skripsi. Buku ini disusun dengan bahasa yang mudah dipahami dan disertai dengan contoh serta tips praktis yang akan sangat membantu dalam memecahkan berbagai kendala yang sering dihadapi mahasiswa selama proses penulisan skripsi. Di awal buku, pembaca akan dibawa untuk memahami konsep-konsep dasar skripsi dan perbedaannya dengan karya ilmiah lainnya. Kemudian, dilanjutkan dengan pembahasan secara mendetil mengenai posisi skripsi dalam kurikulum Fakultas Psikologi Universitas YARSI. Pembahasannya meliputi persyaratan serta prosedur teknis pendaftaran ujian skripsi.

Setelah membahas konsep dasar dan posisi skripsi dalam kurikulum, buku ini akan memandu pembaca menyelami prinsip-prinsip penting yang harus dikuasai mahasiswa untuk memulai petualangannya dalam menulis skripsi. Salah satu kunci sukses dalam penulisan skripsi adalah pemilihan topik. Topik yang dipilih tidak hanya harus sesuai dengan minat dan keahlian mahasiswa, tetapi juga relevan dengan bidang ilmu pengetahuan yang sedang dikaji. Topik yang baik adalah topik yang dapat memberikan kontribusi bagi pengembangan ilmu pengetahuan, sekaligus mampu menjawab masalah aktual yang ada di masyarakat. Dalam buku ini, pembaca akan diajak untuk memahami berbagai pertimbangan dalam memilih topik skripsi, serta strategi dalam mengembangkan ide penelitian menjadi sebuah proposal penelitian yang solid dan meyakinkan.

Selanjutnya, buku ini juga akan membahas secara sekilas mengenai teknik pengumpulan data, baik kualitatif maupun kuantitatif, serta cara-cara untuk menganalisis data tersebut. Mahasiswa akan diajarkan bagaimana cara menginterpretasikan hasil penelitian dan menyajikannya dalam bentuk narasi ilmiah yang koheren dan logis. Selain itu, aspek penting lainnya seperti penulisan daftar pustaka, pengutipan sumber, dan penyusunan lampiran juga akan dibahas untuk memastikan bahwa skripsi yang dihasilkan tidak hanya berkualitas tinggi dari segi konten, tetapi juga memenuhi standar akademik yang berlaku.

Dengan memahami isi dari buku ini, diharapkan mahasiswa dapat menavigasi proses penulisan skripsi dengan lebih mudah dan efisien, serta pada akhirnya dapat menghasilkan skripsi yang tidak hanya memenuhi standar akademik, tetapi juga dapat menjadi kontribusi yang berarti bagi pengembangan ilmu pengetahuan dan masyarakat.

::: {.content-visible when-format="html"}
```{=html}
<p style="text-align: right;"><strong>Tim Penulis</strong>,</p>
<p style="text-align: right;">Juni 2024</p>
```
:::

\

::: {.content-visible when-format="pdf"}
**Tim Penulis**,

Agustus 2024
:::
